
title: test-theme
description: A simple website template
baseurl: "/test-theme" # the subpath of your site, e.g. /blog
url: "https://jstewart7.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
  style: compressed

paginate: 5

owner:
  name: Jacob Stewart
  email: jstewart.socialmedia@gmail.com
  github: https://github.com/jstewart7
  twitter: https://twitter.com/jstewa7

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
